name: Ruff and uv

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    env:
      UV_PYTHON: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ matrix.python-version }}
        version: "0.8.17"
    - name: "Set up Python"
      run: uv python install
    - name: Install dependencies
      run: uv sync --locked --all-extras --dev
    - name: Analysing the code with Ruff
      run: uv run ruff $(git ls-files '*.py')
